/* Sanskrit
var nm9 = ["Abhi","Aca","Adra","Agni","Ahi","Aji","Ali","Ami","Ana","Anga","Anu","Ari","Asa","Avi","Ba","Bha","Bhaga","Bhaya","Bra","Bri","Ca","Can","Canda","Candra","Cha","Ci","Cira","Dan","Danda","Dar","Deva","Dha","Dhar","Dri","Dur","Eka","Gana","Gara","Gau","Gho","Ghu","Go","Gopa","Govin","Hari","Havi","Hra","Hrit","In","Indra","Jai","Jih","Ka","Kal","Kalma","Kapa","Karna","Katu","Kha","Khan","Ko","Kra","Kse","Ksema","Ma","Maha","Man","Mana","Mata","Mayu","Mit","Mitra","Na","Naga","Nai","Nan","Nara","Nir","Nira","Nri","Pa","Para","Pashu","Patta","Pavi","Pra","Praba","Praka","Pram","Prasan","Prati","Pre","Puru","Raja","Rana","Rau","Raudra","Ri","Rita","Ruci","Rudra","Sada","Sahi","Sakra","Sapta","Sarpa","Sasthi","Satya","Sena","Sha","Shaka","Sham","Shan","Sharva","Shi","Shri","Soma","Su","Suda","Sula","Suma","Sumna","Sun","Supa","Supra","Sura","Suru","Susa","Susha","Suva","Suvar","Suvarna","Sva","Svar","Ta","Tan","Tapa","Tapo","Tara","Tra","Trasa","Ugra","Usan","Uta","Va","Vadan","Vaja","Valgu","Vama","Var","Vara","Vasa","Vata","Vatsa","Vayu","Vibha","Vica","Vida","Vidan","Vik","Vina","Visnu","Yajna","Yama"];
var nm10 = ["bahu","bali","bandhu","barhis","basha","bhanu","bhauma","bhojin","candra","caru","cas","daman","darshin","datta","deva","dhaman","dhana","dharman","dhurti","din","dogi","dosa","duta","gava","gavant","griva","gupta","hargava","harman","harsana","hatru","hava","haya","husa","huti","jihvi","jit","kara","kari","karman","karna","karni","kayu","ketu","kratu","lina","locana","malin","man","manas","mant","manyu","mardin","mati","maya","medhas","meyu","mitra","murti","nabahu","nandin","navant","neya","nivant","numant","padda","pala","pani","parvan","pati","pin","rant","rapad","rasetu","ratha","rathi","ravas","retas","rish","riti","ritu","romen","saka","sana","sarathi","setu","shanti","shin","shri","sin","tagni","taksa","tanu","tas","tatman","tavant","tavid","tejas","teyu","thin","timant","tipin","tumant","vaku","vamin","van","vant","varcas","varman","vavan","vid","vis","visnu","vrit","yati","yoni"];
var nm11 = ["Aban","Adri","Aha","Aksa","Alam","Ama","Ambi","Amri","Ana","Ani","Apa","Arci","Arun","As","Asva","Ba","Badhi","Bahu","Bala","Balan","Ban","Bha","Bhanu","Bin","Caru","Ci","Citra","Da","Dama","De","Deva","Dha","Dhar","Dhe","Dhri","Dhu","Dru","Dva","Dvara","Ga","Gan","Gau","Gho","Ghu","Ghur","Giri","Go","Gopi","Ha","Hai","Ham","Harsi","Jan","Jati","Jaya","Ka","Kada","Kaku","Kala","Kam","Kama","Kha","Kri","Ku","Kun","La","Lak","Ma","Mada","Mai","Mali","Mama","Man","Mu","Na","Nan","Ni","Pin","Pra","Praja","Pri","Pura","Raja","Rama","Ranga","Rastra","Ratha","Renu","Rohi","Rudra","Saha","Sara","Sarpa","Satya","Sava","Savi","Sha","Shala","Shi","Shru","Shu","Su","Subha","Sude","Sudha","Suka","Suke","Suku","Sun","Suna","Suro","Sushi","Suta","Sva","Tam","Tamra","Ugra","Upa","Urja","Urmi","Utta","Va","Vada","Vahi","Vajra","Vapu","Var","Vi","Ya","Yasho"];
var nm12 = ["ba","bari","bhadra","bika","busa","cana","dala","damba","dari","dava","deva","devi","dhati","di","gada","gala","gupta","haka","hara","hika","hula","ki","laja","laka","lasa","lata","lekha","lika","lini","ma","mada","maki","mala","mana","mari","matha","mati","matta","mila","mini","na","nanda","ni","nika","nuka","pali","ra","raji","raka","ranta","rashana","rava","reyi","rici","rika","rita","rusi","sa","sala","shana","sini","ta","taci","tama","tara","thara","ti","vaka","vala","varna","vasi","vati","vi","yaka","yani","yanti"];
 Hittite */
export const TYRANIDES_M1: string[] = ["Abbi","Aki","Allu","Am","Amba","Ammi","Ammu","Ani","Anu","Arnu","Awa","Biya","Gil","Hal","Halpa","Han","Hasa","Hasam","Hat","Hattu","Himui","Hupa","Hute","Hutel","Kali","Kha","Khal","Khalpa","Khat","Kil","Ku","Kuli","Kuru","Kuwa","La","Laba","Mamma","Mana","Mashui","Mastu","Mur","Mursi","Muwa","Nena","Pi","Piya","Shadi","Suppi","Tar","Tarhun","Tarka","Tele","Tudha","Tutha","Ua","Uassur","Ulli","Urhi","Uri","Uskhi","Wal","Wari","Wassu","Wasu","Zanna","Zida","Zitha"];
export const TYRANIDES_M2: string[] = ["baris","daraba","haliya","hatna","hunnas","hunt","hunta","ki","li","lia","lis","litta","liuma","liumas","liya","lubi","lupi","luwa","mali","meli","muna","nas","nawa","netta","pash","pinu","radu","radus","riki","riku","rimme","ris","riya","runta","runtas","sarma","shub","sili","silis","siya","sulubi","sulupi","ta","talis","tas","tena","teshup","ti","tili","waili","wamna","wanda","wanza","zili","ziti","ziya"];
export const TYRANIDES_F1: string[] = ["Ane","Anne","Asmu","Da","Dadu","Danu","Es","Ga","Gassu","Gi","Gilu","Ha","Hara","He","Hen","Il","Ila","Istu","Ka","Mas","Massa","Mu","Muwa","Ni","Nika","Pa","Papa","Pu","Pudu","Sin","Ta","Tadu","Tatu","Tawa","Te","Wa","Wala","Walan","Wu","Wuru"];
export const TYRANIDES_F2: string[] = ["bat","hepa","hipa","khepa","la","lanni","lawiya","mati","na","nanna","nauzzi","nella","pa","paya","ra","rinna","semu","shi","sili","tan","taya","tayara","ti","wiya","ya","yara","zi"];
