import {MetalStatut} from "../types/statut_social/Statut";
import {Perso} from "../types/perso/Perso";
import {Carriere, MetierObj} from "../types/metiers/Metier";
import {Option} from "../types/lieux/Lieu";
import {Vertus, Vices} from "../types/ViceVertu";

export enum metiersEnum {
    edile = "Édile",
    macon = "Maçon",
    pilleur_de_ruche = "Pilleur de ruches",
    ranconneur = "Rançonneur",
    serveur = "Serveur",
    novice_pretre = "Moine novice",
    moine = "Moine",
    initie_pretre = "Initié prêtre",
    pretre = "Prêtre",
    etudiant_ingenieur = "Étudiant ingénieur",
    ingenieur = "Ingénieur",
    batelier = "Batelier",
    apprenti_Forgeron = "Apprenti forgeron",
    forgeron = "Forgeron",
    apprenti_brasseur = "Apprenti brasseur",
    brasseur = "Brasseur",
    apprenti_boulanger = "Apprenti boulanger",
    boulanger = "Boulanger",
    apprenti_boucher = "Apprenti boucher",
    boucher = "boucher",
    apprenti_chirurgien = "Apprenti barbier chirurgien",
    chirurgien = "Barbier chirurgien",
    gladiateur = "Gladiateur",
    pamphletaire = "Pamphlétaire",
    stalker = "Stalker",
    mecanicien = "Mécanicien",
    medecin = "Médecin",
    cyberneticien = "Cybernéticien",
    // -------------- métiers orks ------------------ //
    marchand_de_champignon = "Marchand de champignon",

    //-------------------
    non_travailleur = "Ne travaille pas",
}

export const metiersEnumOptions: Option[] =
    Object.values(metiersEnum)
        .map((metier: metiersEnum):Option => {
            return {
                value: metier,
                label: metier.toString(),
            }
        });

export const metiersObjs: MetierObj = {
    // citadins
    [metiersEnum.pamphletaire] : {
        nom: metiersEnum.pamphletaire,
        intitule: () => metiersEnum.pamphletaire,
        statut: {rang: 1, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 5, metalStatut: MetalStatut.bronze},
        proba: 0.1,
        vicesCompatibles: [Vices.trompeur, Vices.rebelle, Vices.aventureux],
        vertusCompatibles: [Vertus.sociable],
    },

    // ------ ------- artisans
    [metiersEnum.etudiant_ingenieur] : {
        nom: metiersEnum.etudiant_ingenieur,
        intitule: () => metiersEnum.etudiant_ingenieur,
        statut: {rang: 2, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 5, metalStatut: MetalStatut.bronze},
        proba: 0.1,
        vicesCompatibles: [],
        vertusCompatibles: [Vertus.artificialiste, Vertus.travailleur],
    },
    [metiersEnum.apprenti_Forgeron] : {
        nom: metiersEnum.apprenti_Forgeron,
        intitule: () => metiersEnum.apprenti_Forgeron,
        statut: {rang: 2, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 5, metalStatut: MetalStatut.bronze},
        proba: 0.1,
        vicesCompatibles: [],
        vertusCompatibles: [Vertus.artificialiste, Vertus.travailleur],
    },
    [metiersEnum.apprenti_brasseur] : {
        nom: metiersEnum.apprenti_brasseur,
        intitule: () => metiersEnum.apprenti_brasseur,
        statut: {rang: 2, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 5, metalStatut: MetalStatut.bronze},
        proba: 0.3,
        vicesCompatibles: [Vices.gourmand],
        vertusCompatibles: [Vertus.travailleur],
    },
    [metiersEnum.apprenti_boulanger] : {
        nom: metiersEnum.apprenti_boulanger,
        intitule: () => metiersEnum.apprenti_boulanger,
        statut: {rang: 2, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 5, metalStatut: MetalStatut.bronze},
        proba: 0.3,
        vicesCompatibles: [Vices.gourmand],
        vertusCompatibles: [Vertus.travailleur],
    },
    [metiersEnum.apprenti_boucher] : {
        nom: metiersEnum.apprenti_boucher,
        intitule: () => metiersEnum.apprenti_boucher,
        statut: {rang: 2, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 5, metalStatut: MetalStatut.bronze},
        proba: 0.3,
        vicesCompatibles: [Vices.gourmand],
        vertusCompatibles: [Vertus.travailleur],
    },
    [metiersEnum.ingenieur] : {
        nom: metiersEnum.ingenieur,
        intitule: () => metiersEnum.ingenieur,
        statut: {rang: 2, metalStatut: MetalStatut.argent},
        statutMax: {rang: 2, metalStatut: MetalStatut.or},
        proba: 0.5,
        vicesCompatibles: [],
        vertusCompatibles: [Vertus.artificialiste],
    },
    [metiersEnum.forgeron] : {
        nom: metiersEnum.forgeron,
        intitule: () => metiersEnum.forgeron,
        statut: {rang: 1, metalStatut: MetalStatut.argent},
        statutMax: {rang: 1, metalStatut: MetalStatut.or},
        proba: 0.3,
        vicesCompatibles: [Vices.gourmand],
        vertusCompatibles: [Vertus.travailleur],
    },
    [metiersEnum.macon] : {
        nom: metiersEnum.macon,
        intitule: () => metiersEnum.macon,
        statut: {rang: 2, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 2, metalStatut: MetalStatut.argent},
        proba: 0.8,
        vicesCompatibles: [],
        vertusCompatibles: [Vertus.artificialiste, Vertus.travailleur],
    },
    [metiersEnum.brasseur] : {
        nom: metiersEnum.brasseur,
        intitule: () => metiersEnum.brasseur,
        statut: {rang: 1, metalStatut: MetalStatut.argent},
        statutMax: {rang: 1, metalStatut: MetalStatut.or},
        proba: 0.5,
        vicesCompatibles: [Vices.gourmand],
        vertusCompatibles: [Vertus.travailleur],
    },
    [metiersEnum.boulanger] : {
        nom: metiersEnum.boulanger,
        intitule: () => metiersEnum.boulanger,
        statut: {rang: 1, metalStatut: MetalStatut.argent},
        statutMax: {rang: 1, metalStatut: MetalStatut.or},
        proba: 0.5,
        vicesCompatibles: [Vices.gourmand],
        vertusCompatibles: [Vertus.travailleur],
    },
    [metiersEnum.boucher] : {
        nom: metiersEnum.boucher,
        intitule: () => metiersEnum.boucher,
        statut: {rang: 1, metalStatut: MetalStatut.argent},
        statutMax: {rang: 1, metalStatut: MetalStatut.or},
        proba: 0.5,
        vicesCompatibles: [Vices.gourmand],
        vertusCompatibles: [Vertus.travailleur],
    },
    [metiersEnum.marchand_de_champignon] : {
        nom: metiersEnum.marchand_de_champignon,
        intitule: () => metiersEnum.marchand_de_champignon,
        statut: {rang: 2, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 1, metalStatut: MetalStatut.argent},
        proba: 0.1,
        vicesCompatibles: [Vices.cupide, Vices.naturaliste],
        vertusCompatibles: [],
    },
    [metiersEnum.apprenti_chirurgien] : {
        nom: metiersEnum.apprenti_chirurgien,
        intitule: () => metiersEnum.apprenti_chirurgien,
        statut: {rang: 3, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 1, metalStatut: MetalStatut.argent},
        proba: 0.1,
        vicesCompatibles: [Vices.sociopathique, Vices.orgueilleux],
        vertusCompatibles: [Vertus.prudent],
    },
    [metiersEnum.chirurgien] : {
        nom: metiersEnum.chirurgien,
        intitule: () => metiersEnum.chirurgien,
        statut: {rang: 3, metalStatut: MetalStatut.argent},
        statutMax: {rang: 1, metalStatut: MetalStatut.or},
        proba: 0.2,
        vicesCompatibles: [Vices.sociopathique, Vices.orgueilleux],
        vertusCompatibles: [Vertus.prudent],
    },
    [metiersEnum.gladiateur] : {
        nom: metiersEnum.gladiateur,
        intitule: () => metiersEnum.gladiateur,
        statut: {rang: 0, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 3, metalStatut: MetalStatut.argent},
        proba: 0.1,
        vicesCompatibles: [Vices.colerique, Vices.cruel],
        vertusCompatibles: [Vertus.valeureux],
    },
    [metiersEnum.batelier] : {
        nom: metiersEnum.batelier,
        intitule: () => metiersEnum.batelier,
        statut: {rang: 1, metalStatut: MetalStatut.argent},
        statutMax: {rang: 5, metalStatut: MetalStatut.argent},
        proba: 0.5,
        vicesCompatibles: [],
        vertusCompatibles: [Vertus.placide, Vertus.sociable],
    },
    [metiersEnum.serveur] : {
        nom: metiersEnum.serveur,
        intitule: (_perso: Perso, carriere: Carriere) => {
            return metiersEnum.serveur + " à " + carriere?.groupeLieu;
        },
        statut: {rang: 2, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 2, metalStatut: MetalStatut.argent},
        proba: 0.8,
        vicesCompatibles: [],
        vertusCompatibles: [Vertus.sociable],
    },
    [metiersEnum.edile] : {
        nom: metiersEnum.edile,
        intitule: (_perso: Perso, carriere: Carriere) => {
            return metiersEnum.edile + (carriere ? " à " : "") + carriere?.groupeLieu;
        },
        statut: {rang: 4, metalStatut: MetalStatut.argent},
        statutMax: {rang: 1, metalStatut: MetalStatut.or},
        proba: 0.1,
        vicesCompatibles: [],
        vertusCompatibles: [Vertus.sociable],
    },
    [metiersEnum.ranconneur] : {
        nom: metiersEnum.ranconneur,
        intitule: () => metiersEnum.ranconneur,
        statut: {rang: 3, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 5, metalStatut: MetalStatut.argent},
        proba: 0.3,
        vicesCompatibles: [Vices.colerique, Vices.cruel, Vices.trompeur],
        vertusCompatibles: [],
    },
    [metiersEnum.novice_pretre] : {
        nom: metiersEnum.novice_pretre,
        intitule: (perso: Perso) => {
            return metiersEnum.novice_pretre + " de " + perso.dieu.id;
        },
        statut: {rang: 1, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 2, metalStatut: MetalStatut.bronze},
        proba: 0.2,
        vicesCompatibles: [],
        vertusCompatibles: [Vertus.chaste, Vertus.spirituel],
    },
    [metiersEnum.initie_pretre] : {
        nom: metiersEnum.initie_pretre,
        intitule: (perso: Perso) => metiersEnum.initie_pretre + " de " + perso.dieu.id,
        statut: {rang: 2, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 4, metalStatut: MetalStatut.bronze},
        proba: 0.3,
        vicesCompatibles: [],
        vertusCompatibles: [Vertus.chaste, Vertus.spirituel],
    },
    [metiersEnum.moine] : {
        nom: metiersEnum.moine,
        intitule: (perso: Perso) => metiersEnum.moine + " de " + perso.dieu.id,
        statut: {rang: 4, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 5, metalStatut: MetalStatut.argent},
        proba: 0.3,
        vicesCompatibles: [],
        vertusCompatibles: [Vertus.chaste, Vertus.spirituel],
    },
    [metiersEnum.pretre] : {
        nom: metiersEnum.pretre,
        intitule: (perso: Perso) => metiersEnum.pretre + " de " + perso.dieu.id,
        statut: {rang: 1, metalStatut: MetalStatut.argent},
        statutMax: {rang: 2, metalStatut: MetalStatut.or},
        proba: 0.3,
        vicesCompatibles: [],
        vertusCompatibles: [Vertus.chaste, Vertus.spirituel],
    },
    [metiersEnum.stalker] : {
        nom: metiersEnum.stalker,
        intitule: (_perso: Perso, _carriere: Carriere) => metiersEnum.stalker,
        statut: {rang: 2, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 4, metalStatut: MetalStatut.argent},
        proba: 0,
        vicesCompatibles: [Vices.rebelle, Vices.aventureux],
        vertusCompatibles: [Vertus.valeureux],
    },
    [metiersEnum.mecanicien] : {
        nom: metiersEnum.mecanicien,
        intitule: (_perso: Perso, _carriere: Carriere) => metiersEnum.mecanicien,
        statut: {rang: 5, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 1, metalStatut: MetalStatut.or},
        proba: 0.5,
        vicesCompatibles: [],
        vertusCompatibles: [Vertus.artificialiste, Vertus.travailleur],
    },
    [metiersEnum.medecin] : {
        nom: metiersEnum.medecin,
        intitule: (_perso: Perso, _carriere: Carriere) => metiersEnum.medecin,
        statut: {rang: 2, metalStatut: MetalStatut.argent},
        statutMax: {rang: 3, metalStatut: MetalStatut.or},
        proba: 0.5,
        vicesCompatibles: [],
        vertusCompatibles: [Vertus.prudent],
    },
    [metiersEnum.cyberneticien] : {
        nom: metiersEnum.cyberneticien,
        intitule: (_perso: Perso, _carriere: Carriere) => metiersEnum.cyberneticien,
        statut: {rang: 2, metalStatut: MetalStatut.argent},
        statutMax: {rang: 3, metalStatut: MetalStatut.or},
        proba: 0.1,
        vicesCompatibles: [],
        vertusCompatibles: [Vertus.prudent, Vertus.artificialiste],
    },
    [metiersEnum.pilleur_de_ruche] : {
        nom: metiersEnum.pilleur_de_ruche,
        intitule: (_perso: Perso, _carriere: Carriere) => metiersEnum.pilleur_de_ruche,
        statut: {rang: 2, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 4, metalStatut: MetalStatut.argent},
        proba: 0,
        vicesCompatibles: [Vices.cupide, Vices.aventureux],
        vertusCompatibles: [Vertus.valeureux],
    },
    [metiersEnum.non_travailleur] : {
        nom: metiersEnum.non_travailleur,
        intitule: (_perso: Perso, _carriere: Carriere) => metiersEnum.non_travailleur,
        statut: {rang: 0, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 3, metalStatut: MetalStatut.bronze},
        proba: 0.5,
        vicesCompatibles: [Vices.paresseux],
        vertusCompatibles: [],
    },
}