import {MetalStatut} from "../types/statut_social/Statut";
import {Perso} from "../types/perso/Perso";
import {Carriere, MetierObj} from "../types/metiers/Metier";
import {Option} from "../types/lieux/Lieu";
import {Vertu, Vice} from "../types/ViceVertu";

export enum MetiersEnum {
    edile = "Édile",
    macon = "Maçon",
    plombier = "Plombier",
    pilleur_de_ruche = "Pilleur de ruches",
    ranconneur = "Rançonneur",
    serveur = "Serveur",
    novice_pretre = "Moine novice",
    moine = "Moine",
    initie_pretre = "Initié prêtre",
    pretre = "Prêtre",
    etudiant_ingenieur = "Étudiant ingénieur",
    ingenieur = "Ingénieur",
    batelier = "Batelier",
    journaliste = "Journaliste",
    ecrivain = "Écrivain",
    apprenti_brasseur = "Apprenti brasseur",
    brasseur = "Brasseur",
    apprenti_boulanger = "Apprenti boulanger",
    boulanger = "Boulanger",
    apprenti_boucher = "Apprenti boucher",
    boucher = "boucher",
    apprenti_chirurgien = "Étudiant chirurgien",
    chirurgien = "Chirurgien",
    gladiateur = "Gladiateur",
    pamphletaire = "Pamphlétaire",
    stalker = "Stalker",
    mecanicien = "Mécanicien",
    medecin = "Médecin",
    cyberneticien = "Cybernéticien",
    informaticien = "Informaticien", // programmeur, responsable réseau etc au sens large
    magicien = "Magicien", // inclut pour l'instant tous les magiciens (nécromanciens compris)
    technomancien = "Technomancen",
    // -------------- métiers orks ------------------ //
    marchand_de_champignon = "Marchand de champignon",

    //  pas ne vraie carrière : plutôt de grosses occupations en plus du lycée
    brute_de_lycee = "Brute de lycée",
    dileur_de_lycee = "Dileur de lycée",

    //-------------------
    non_travailleur = "Ne travaille pas",
}

/**
 * métiers qu'on exerce pendant ses études, inclus els activités qui ne sont aps réellement des métiers comme les magouilles, racketx etc
 * On ne peut pas négocier pour y être augmenté
 */
export const metiersDEtudiants: MetiersEnum[] = [MetiersEnum.dileur_de_lycee, MetiersEnum.brute_de_lycee];

export const metiersEnumOptions: Option[] =
    Object.values(MetiersEnum)
        .map((metier: MetiersEnum):Option => {
            return {
                value: metier,
                label: metier.toString(),
            }
        });

export const metiersObjs: MetierObj = {
    // citadins
    [MetiersEnum.pamphletaire] : {
        nom: MetiersEnum.pamphletaire,
        intitule: () => MetiersEnum.pamphletaire,
        statut: {rang: 1, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 5, metalStatut: MetalStatut.bronze},
        proba: 0.1,
        vicesCompatibles: [Vice.trompeur, Vice.rebelle, Vice.aventureux],
        vertusCompatibles: [Vertu.sociable],
    },

    // ------ ------- artisans
    [MetiersEnum.etudiant_ingenieur] : {
        nom: MetiersEnum.etudiant_ingenieur,
        intitule: () => MetiersEnum.etudiant_ingenieur,
        statut: {rang: 2, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 5, metalStatut: MetalStatut.bronze},
        proba: 0.1,
        vicesCompatibles: [],
        vertusCompatibles: [Vertu.artificialiste, Vertu.travailleur],
    },
    [MetiersEnum.apprenti_brasseur] : {
        nom: MetiersEnum.apprenti_brasseur,
        intitule: () => MetiersEnum.apprenti_brasseur,
        statut: {rang: 2, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 5, metalStatut: MetalStatut.bronze},
        proba: 0.3,
        vicesCompatibles: [Vice.gourmand],
        vertusCompatibles: [Vertu.travailleur],
    },
    [MetiersEnum.apprenti_boulanger] : {
        nom: MetiersEnum.apprenti_boulanger,
        intitule: () => MetiersEnum.apprenti_boulanger,
        statut: {rang: 2, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 5, metalStatut: MetalStatut.bronze},
        proba: 0.3,
        vicesCompatibles: [Vice.gourmand],
        vertusCompatibles: [Vertu.travailleur],
    },
    [MetiersEnum.apprenti_boucher] : {
        nom: MetiersEnum.apprenti_boucher,
        intitule: () => MetiersEnum.apprenti_boucher,
        statut: {rang: 2, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 5, metalStatut: MetalStatut.bronze},
        proba: 0.3,
        vicesCompatibles: [Vice.gourmand],
        vertusCompatibles: [Vertu.travailleur],
    },
    [MetiersEnum.ingenieur] : {
        nom: MetiersEnum.ingenieur,
        intitule: () => MetiersEnum.ingenieur,
        statut: {rang: 2, metalStatut: MetalStatut.argent},
        statutMax: {rang: 2, metalStatut: MetalStatut.or},
        proba: 0.5,
        vicesCompatibles: [],
        vertusCompatibles: [Vertu.artificialiste],
    },
    [MetiersEnum.macon] : {
        nom: MetiersEnum.macon,
        intitule: () => MetiersEnum.macon,
        statut: {rang: 2, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 2, metalStatut: MetalStatut.argent},
        proba: 0.8,
        vicesCompatibles: [],
        vertusCompatibles: [Vertu.artificialiste, Vertu.travailleur],
    },
    [MetiersEnum.plombier] : {
        nom: MetiersEnum.plombier,
        intitule: () => MetiersEnum.plombier,
        statut: {rang: 3, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 5, metalStatut: MetalStatut.argent},
        proba: 0.8,
        vicesCompatibles: [],
        vertusCompatibles: [Vertu.artificialiste, Vertu.reflechi, Vertu.prudent],
    },
    [MetiersEnum.brasseur] : {
        nom: MetiersEnum.brasseur,
        intitule: () => MetiersEnum.brasseur,
        statut: {rang: 1, metalStatut: MetalStatut.argent},
        statutMax: {rang: 1, metalStatut: MetalStatut.or},
        proba: 0.5,
        vicesCompatibles: [Vice.gourmand],
        vertusCompatibles: [Vertu.travailleur],
    },
    [MetiersEnum.boulanger] : {
        nom: MetiersEnum.boulanger,
        intitule: () => MetiersEnum.boulanger,
        statut: {rang: 1, metalStatut: MetalStatut.argent},
        statutMax: {rang: 1, metalStatut: MetalStatut.or},
        proba: 0.5,
        vicesCompatibles: [Vice.gourmand],
        vertusCompatibles: [Vertu.travailleur],
    },
    [MetiersEnum.boucher] : {
        nom: MetiersEnum.boucher,
        intitule: () => MetiersEnum.boucher,
        statut: {rang: 1, metalStatut: MetalStatut.argent},
        statutMax: {rang: 1, metalStatut: MetalStatut.or},
        proba: 0.5,
        vicesCompatibles: [Vice.gourmand],
        vertusCompatibles: [Vertu.travailleur],
    },
    [MetiersEnum.marchand_de_champignon] : {
        nom: MetiersEnum.marchand_de_champignon,
        intitule: () => MetiersEnum.marchand_de_champignon,
        statut: {rang: 2, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 1, metalStatut: MetalStatut.argent},
        proba: 0.1,
        vicesCompatibles: [Vice.cupide, Vice.naturaliste],
        vertusCompatibles: [],
    },
    [MetiersEnum.apprenti_chirurgien] : {
        nom: MetiersEnum.apprenti_chirurgien,
        intitule: () => MetiersEnum.apprenti_chirurgien,
        statut: {rang: 3, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 1, metalStatut: MetalStatut.argent},
        proba: 0.1,
        vicesCompatibles: [Vice.sociopathique, Vice.orgueilleux],
        vertusCompatibles: [Vertu.prudent],
    },
    [MetiersEnum.chirurgien] : {
        nom: MetiersEnum.chirurgien,
        intitule: () => MetiersEnum.chirurgien,
        statut: {rang: 3, metalStatut: MetalStatut.argent},
        statutMax: {rang: 1, metalStatut: MetalStatut.or},
        proba: 0.2,
        vicesCompatibles: [Vice.sociopathique, Vice.orgueilleux],
        vertusCompatibles: [Vertu.prudent],
    },
    [MetiersEnum.gladiateur] : {
        nom: MetiersEnum.gladiateur,
        intitule: () => MetiersEnum.gladiateur,
        statut: {rang: 0, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 3, metalStatut: MetalStatut.argent},
        proba: 0.1,
        vicesCompatibles: [Vice.colerique, Vice.cruel],
        vertusCompatibles: [Vertu.valeureux],
    },
    [MetiersEnum.batelier] : {
        nom: MetiersEnum.batelier,
        intitule: () => MetiersEnum.batelier,
        statut: {rang: 1, metalStatut: MetalStatut.argent},
        statutMax: {rang: 5, metalStatut: MetalStatut.argent},
        proba: 0.5,
        vicesCompatibles: [],
        vertusCompatibles: [Vertu.placide, Vertu.sociable],
    },
    [MetiersEnum.journaliste] : {
        nom: MetiersEnum.journaliste,
        intitule: () => MetiersEnum.journaliste,
        statut: {rang: 4, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 5, metalStatut: MetalStatut.argent},
        proba: 0.3,
        vicesCompatibles: [Vice.trompeur, Vice.mefiant, Vice.sceptique],
        vertusCompatibles: [Vertu.sociable],
    },
    [MetiersEnum.ecrivain] : {
        nom: MetiersEnum.ecrivain,
        intitule: () => MetiersEnum.ecrivain,
        statut: {rang: 3, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 1, metalStatut: MetalStatut.or},
        proba: 0.15,
        vicesCompatibles: [Vice.solitaire],
        vertusCompatibles: [],
    },
    [MetiersEnum.serveur] : {
        nom: MetiersEnum.serveur,
        intitule: (_perso: Perso, carriere: Carriere) => {
            return MetiersEnum.serveur + " à " + carriere?.groupeLieu;
        },
        statut: {rang: 2, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 2, metalStatut: MetalStatut.argent},
        proba: 0.8,
        vicesCompatibles: [],
        vertusCompatibles: [Vertu.sociable],
    },
    [MetiersEnum.edile] : {
        nom: MetiersEnum.edile,
        intitule: (_perso: Perso, carriere: Carriere) => {
            return MetiersEnum.edile + (carriere ? " à " : "") + carriere?.groupeLieu;
        },
        statut: {rang: 4, metalStatut: MetalStatut.argent},
        statutMax: {rang: 1, metalStatut: MetalStatut.or},
        proba: 0.1,
        vicesCompatibles: [],
        vertusCompatibles: [Vertu.sociable],
    },
    [MetiersEnum.ranconneur] : {
        nom: MetiersEnum.ranconneur,
        intitule: () => MetiersEnum.ranconneur,
        statut: {rang: 3, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 5, metalStatut: MetalStatut.argent},
        proba: 0.3,
        vicesCompatibles: [Vice.colerique, Vice.cruel, Vice.trompeur, Vice.sociopathique],
        vertusCompatibles: [],
    },
    [MetiersEnum.brute_de_lycee] : {
        nom: MetiersEnum.brute_de_lycee,
        intitule: () => MetiersEnum.brute_de_lycee,
        statut: {rang: 1, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 4, metalStatut: MetalStatut.bronze},
        proba: 0.01,
        vicesCompatibles: [Vice.colerique, Vice.cruel, Vice.sociopathique],
        vertusCompatibles: [],
    },
    [MetiersEnum.dileur_de_lycee] : {
        nom: MetiersEnum.dileur_de_lycee,
        intitule: () => MetiersEnum.dileur_de_lycee,
        statut: {rang: 2, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 1, metalStatut: MetalStatut.argent},
        proba: 0.01,
        vicesCompatibles: [Vice.trompeur, Vice.sociopathique, Vice.rebelle, Vice.gourmand, Vice.paresseux],
        vertusCompatibles: [Vertu.sociable],
    },
    [MetiersEnum.novice_pretre] : {
        nom: MetiersEnum.novice_pretre,
        intitule: (perso: Perso) => {
            return MetiersEnum.novice_pretre + " de " + perso.religion;
        },
        statut: {rang: 1, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 2, metalStatut: MetalStatut.bronze},
        proba: 0.2,
        vicesCompatibles: [],
        vertusCompatibles: [Vertu.chaste, Vertu.spirituel],
    },
    [MetiersEnum.initie_pretre] : {
        nom: MetiersEnum.initie_pretre,
        intitule: (perso: Perso) => MetiersEnum.initie_pretre + " de " + perso.religion,
        statut: {rang: 2, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 4, metalStatut: MetalStatut.bronze},
        proba: 0.3,
        vicesCompatibles: [],
        vertusCompatibles: [Vertu.chaste, Vertu.spirituel],
    },
    [MetiersEnum.moine] : {
        nom: MetiersEnum.moine,
        intitule: (perso: Perso) => MetiersEnum.moine + " de " + perso.religion,
        statut: {rang: 4, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 5, metalStatut: MetalStatut.argent},
        proba: 0.3,
        vicesCompatibles: [],
        vertusCompatibles: [Vertu.chaste, Vertu.spirituel],
    },
    [MetiersEnum.pretre] : {
        nom: MetiersEnum.pretre,
        intitule: (perso: Perso) => MetiersEnum.pretre + " de " + perso.religion,
        statut: {rang: 1, metalStatut: MetalStatut.argent},
        statutMax: {rang: 2, metalStatut: MetalStatut.or},
        proba: 0.3,
        vicesCompatibles: [],
        vertusCompatibles: [Vertu.chaste, Vertu.spirituel],
    },
    [MetiersEnum.stalker] : {
        nom: MetiersEnum.stalker,
        intitule: (_perso: Perso, _carriere: Carriere) => MetiersEnum.stalker,
        statut: {rang: 2, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 4, metalStatut: MetalStatut.argent},
        proba: 0,
        vicesCompatibles: [Vice.rebelle, Vice.aventureux],
        vertusCompatibles: [Vertu.valeureux],
    },
    [MetiersEnum.mecanicien] : {
        nom: MetiersEnum.mecanicien,
        intitule: (_perso: Perso, _carriere: Carriere) => MetiersEnum.mecanicien,
        statut: {rang: 5, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 1, metalStatut: MetalStatut.or},
        proba: 0.5,
        vicesCompatibles: [],
        vertusCompatibles: [Vertu.artificialiste, Vertu.travailleur],
    },
    [MetiersEnum.medecin] : {
        nom: MetiersEnum.medecin,
        intitule: (_perso: Perso, _carriere: Carriere) => MetiersEnum.medecin,
        statut: {rang: 2, metalStatut: MetalStatut.argent},
        statutMax: {rang: 3, metalStatut: MetalStatut.or},
        proba: 0.5,
        vicesCompatibles: [],
        vertusCompatibles: [Vertu.prudent],
    },
    [MetiersEnum.cyberneticien] : {
        nom: MetiersEnum.cyberneticien,
        intitule: (_perso: Perso, _carriere: Carriere) => MetiersEnum.cyberneticien,
        statut: {rang: 2, metalStatut: MetalStatut.argent},
        statutMax: {rang: 3, metalStatut: MetalStatut.or},
        proba: 0.1,
        vicesCompatibles: [],
        vertusCompatibles: [Vertu.prudent, Vertu.artificialiste],
    },
    [MetiersEnum.informaticien] : {
        nom: MetiersEnum.informaticien,
        intitule: (_perso: Perso, _carriere: Carriere) => MetiersEnum.informaticien,
        statut: {rang: 2, metalStatut: MetalStatut.argent},
        statutMax: {rang: 1, metalStatut: MetalStatut.or},
        proba: 0.3,
        vicesCompatibles: [],
        vertusCompatibles: [Vertu.prudent, Vertu.artificialiste],
    },
    [MetiersEnum.magicien] : {
        nom: MetiersEnum.magicien,
        intitule: (_perso: Perso, _carriere: Carriere) => MetiersEnum.magicien,
        statut: {rang: 4, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 3, metalStatut: MetalStatut.or},
        proba: 0.01,
        vicesCompatibles: [],
        vertusCompatibles: [],
    },
    [MetiersEnum.technomancien] : {
        nom: MetiersEnum.technomancien,
        intitule: (_perso: Perso, _carriere: Carriere) => MetiersEnum.technomancien,
        statut: {rang: 4, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 3, metalStatut: MetalStatut.or},
        proba: 0.001,
        vicesCompatibles: [],
        vertusCompatibles: [],
    },
    [MetiersEnum.pilleur_de_ruche] : {
        nom: MetiersEnum.pilleur_de_ruche,
        intitule: (_perso: Perso, _carriere: Carriere) => MetiersEnum.pilleur_de_ruche,
        statut: {rang: 2, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 4, metalStatut: MetalStatut.argent},
        proba: 0,
        vicesCompatibles: [Vice.cupide, Vice.aventureux],
        vertusCompatibles: [Vertu.valeureux],
    },
    [MetiersEnum.non_travailleur] : {
        nom: MetiersEnum.non_travailleur,
        intitule: (_perso: Perso, _carriere: Carriere) => MetiersEnum.non_travailleur,
        statut: {rang: 0, metalStatut: MetalStatut.bronze},
        statutMax: {rang: 3, metalStatut: MetalStatut.bronze},
        proba: 0.5,
        vicesCompatibles: [Vice.paresseux],
        vertusCompatibles: [],
    },
}