import {Coterie} from "../../types/Coterie";
import {metiersEnum} from "../metiers";

export const metierFavorisesParCoterie: Record<Coterie, metiersEnum[]> = {
    [Coterie.chaos]: [],
    [Coterie.acheron]: [],
    [Coterie.bastets]: [],
    [Coterie.cathares]: [],
    [Coterie.carthaginois]: [],
    [Coterie.conquistador]: [],
    [Coterie.culte_du_plaisir]:  [],
    [Coterie.esprit_de_la_nature]: [],
    [Coterie.celtes]: [],
    [Coterie.demokratos]: [],
    [Coterie.elfes]: [],
    [Coterie.esthetes]:  [],
    [Coterie.jacobins]: [],
    [Coterie.libertins]: [],
    [Coterie.lumieres]: [metiersEnum.journaliste, metiersEnum.ecrivain],
    [Coterie.ogres]: [],
    [Coterie.orks]: [],
    [Coterie.performeurs]: [],
    [Coterie.romains]: [],
    [Coterie.saabi]: [],
    [Coterie.schweizer]: [],
    [Coterie.skavens]: [],
    [Coterie.templiers]: [],
    [Coterie.transhumanistes]: [],
    [Coterie.tyranides]:  [],
    [Coterie.zaporogues]: []
}

export const metierDetestesParCoterie: Record<Coterie, metiersEnum[]> = {
    [Coterie.chaos]: [],
    [Coterie.acheron]: [],
    [Coterie.bastets]: [],
    [Coterie.cathares]: [],
    [Coterie.carthaginois]: [],
    [Coterie.conquistador]: [],
    [Coterie.culte_du_plaisir]:  [],
    [Coterie.esprit_de_la_nature]: [],
    [Coterie.celtes]: [],
    [Coterie.demokratos]: [],
    [Coterie.elfes]: [],
    [Coterie.esthetes]:  [],
    [Coterie.jacobins]: [],
    [Coterie.libertins]: [],
    [Coterie.lumieres]: [],
    [Coterie.ogres]: [],
    [Coterie.orks]: [],
    [Coterie.performeurs]: [],
    [Coterie.romains]: [],
    [Coterie.saabi]: [],
    [Coterie.schweizer]: [],
    [Coterie.skavens]: [],
    [Coterie.templiers]: [],
    [Coterie.transhumanistes]: [],
    [Coterie.tyranides]:  [],
    [Coterie.zaporogues]: []
}