import {Coterie} from "../../types/Coterie";

export const iconesCot: Record<Coterie, string> = {
    [Coterie.culte_du_plaisir]: "https://raw.githubusercontent.com/gabriellevy/destin-extremis-react/refs/heads/main/images/coteries/icones/Culte%20du%20plaisir.png",
    "Esprit de la nature": "",
    Aucune: "",
    [Coterie.bastets]: "https://raw.githubusercontent.com/gabriellevy/destin-extremis-react/refs/heads/main/images/coteries/icones/Bastet.png",
    [Coterie.carthaginois]: "https://raw.githubusercontent.com/gabriellevy/destin-extremis-react/refs/heads/main/images/coteries/icones/Carthaginois.png",
    [Coterie.cathares]: "https://raw.githubusercontent.com/gabriellevy/destin-extremis-react/refs/heads/main/images/coteries/icones/Cathares.png",
    [Coterie.celtes]: "https://raw.githubusercontent.com/gabriellevy/destin-extremis-react/refs/heads/main/images/coteries/icones/Celte.png",
    [Coterie.chaos]: "",
    [Coterie.conquistador]: "https://raw.githubusercontent.com/gabriellevy/destin-extremis-react/refs/heads/main/images/coteries/icones/Conquistador.png",
    [Coterie.demokratos]: "https://raw.githubusercontent.com/gabriellevy/destin-extremis-react/refs/heads/main/images/coteries/icones/D%C3%A9mokratos.png",
    Elfes: "",
    Esthètes: "",
    Jacobins: "",
    Libertins: "",
    Lumières: "",
    Ogres: "",
    Orks: "",
    Performeurs: "",
    Romains: "",
    Saabi: "",
    Schweizer: "",
    Skavens: "",
    Templiers: "",
    Transhumanistes: "",
    Tyranides: "",
    Zaporogues: "",
    [Coterie.acheron] : "https://raw.githubusercontent.com/gabriellevy/destin-extremis-react/refs/heads/main/images/coteries/icones/Ach%C3%A9ron.png"
}